#!/bin/bash

## JSONRPC
jsonrpc='"2.0"'
id='0'
method='"Deploy"'
main='"print(LOCATION);\n"' lib='{"lib1.ds":"print(1);\n","lib2.ds":"print(2);\n"}'
script='{"main":'$main',"lib":'$lib'}';
meta='{"actionmap":{"E1":{"actiontype":"monitor","reaction":"E2"},"E2":{"actiontype":"normal","reaction":""}}}'
params='{"script":'$script',"meta":'$meta'}'
agent_url='localhost:8081'

function test() {
	local request='{"jsonrpc":'$jsonrpc',"id":'$id',"method":'$method',"params":'$params'}'
	curl -H 'Content-Type: application/json' -d $request $agent_url
}

test
